/*
 * HealthOS.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */
using System;
using HealthOS.UWP.Controllers;
using HealthOS.UWP.Http.Client;

namespace HealthOS.UWP
{
    public partial class HealthOSClient
    {

        /// <summary>
        /// Singleton access to Medicines controller
        /// </summary>
        public MedicinesController Medicines
        {
            get
            {
                return MedicinesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to LabTests controller
        /// </summary>
        public LabTestsController LabTests
        {
            get
            {
                return LabTestsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Generics controller
        /// </summary>
        public GenericsController Generics
        {
            get
            {
                return GenericsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Food controller
        /// </summary>
        public FoodController Food
        {
            get
            {
                return FoodController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Exercises controller
        /// </summary>
        public ExercisesController Exercises
        {
            get
            {
                return ExercisesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to DrugInteractions controller
        /// </summary>
        public DrugInteractionsController DrugInteractions
        {
            get
            {
                return DrugInteractionsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Diseases controller
        /// </summary>
        public DiseasesController Diseases
        {
            get
            {
                return DiseasesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Chat controller
        /// </summary>
        public ChatController Chat
        {
            get
            {
                return ChatController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Autocomplete controller
        /// </summary>
        public AutocompleteController Autocomplete
        {
            get
            {
                return AutocompleteController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Authentication controller
        /// </summary>
        public AuthenticationController Authentication
        {
            get
            {
                return AuthenticationController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public HealthOSClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public HealthOSClient(string host, string oAuthAccessToken)
        {
            Configuration.Host = host;
            Configuration.OAuthAccessToken = oAuthAccessToken;
        }
    }
}