/*
 * HealthOS.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using HealthOS.UWP;
using HealthOS.UWP.Utilities;

namespace HealthOS.UWP.Models
{
    public class AllFoodBrandsResponse : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string brandName;
        private string foodBrandId;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("brand_name")]
        public string BrandName 
        { 
            get 
            {
                return this.brandName; 
            } 
            set 
            {
                this.brandName = value;
                onPropertyChanged("BrandName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("food_brand_id")]
        public string FoodBrandId 
        { 
            get 
            {
                return this.foodBrandId; 
            } 
            set 
            {
                this.foodBrandId = value;
                onPropertyChanged("FoodBrandId");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 