/*
 * HealthOS.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using HealthOS.UWP;
using HealthOS.UWP.Utilities;

namespace HealthOS.UWP.Models
{
    public class AllGenericsResponse : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string name;
        private string pregnancyCategory;
        private string lactationCategory;
        private string instructions;
        private string faqs;
        private int genricId;
        private string sideEffects;
        private string howItWorks;
        private string therapeuticClass;
        private string usedFor;
        private string strength;
        private string schedule;
        private string alcoholInteractionDescription;
        private bool alcoholNteraction;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("pregnancy_category")]
        public string PregnancyCategory 
        { 
            get 
            {
                return this.pregnancyCategory; 
            } 
            set 
            {
                this.pregnancyCategory = value;
                onPropertyChanged("PregnancyCategory");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lactation_category")]
        public string LactationCategory 
        { 
            get 
            {
                return this.lactationCategory; 
            } 
            set 
            {
                this.lactationCategory = value;
                onPropertyChanged("LactationCategory");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("instructions")]
        public string Instructions 
        { 
            get 
            {
                return this.instructions; 
            } 
            set 
            {
                this.instructions = value;
                onPropertyChanged("Instructions");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("faqs")]
        public string Faqs 
        { 
            get 
            {
                return this.faqs; 
            } 
            set 
            {
                this.faqs = value;
                onPropertyChanged("Faqs");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("genric_id")]
        public int GenricId 
        { 
            get 
            {
                return this.genricId; 
            } 
            set 
            {
                this.genricId = value;
                onPropertyChanged("GenricId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("side_effects")]
        public string SideEffects 
        { 
            get 
            {
                return this.sideEffects; 
            } 
            set 
            {
                this.sideEffects = value;
                onPropertyChanged("SideEffects");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("how_it_works")]
        public string HowItWorks 
        { 
            get 
            {
                return this.howItWorks; 
            } 
            set 
            {
                this.howItWorks = value;
                onPropertyChanged("HowItWorks");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("therapeutic_class")]
        public string TherapeuticClass 
        { 
            get 
            {
                return this.therapeuticClass; 
            } 
            set 
            {
                this.therapeuticClass = value;
                onPropertyChanged("TherapeuticClass");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("used_for")]
        public string UsedFor 
        { 
            get 
            {
                return this.usedFor; 
            } 
            set 
            {
                this.usedFor = value;
                onPropertyChanged("UsedFor");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("strength")]
        public string Strength 
        { 
            get 
            {
                return this.strength; 
            } 
            set 
            {
                this.strength = value;
                onPropertyChanged("Strength");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("schedule")]
        public string Schedule 
        { 
            get 
            {
                return this.schedule; 
            } 
            set 
            {
                this.schedule = value;
                onPropertyChanged("Schedule");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("alcohol_interaction_description")]
        public string AlcoholInteractionDescription 
        { 
            get 
            {
                return this.alcoholInteractionDescription; 
            } 
            set 
            {
                this.alcoholInteractionDescription = value;
                onPropertyChanged("AlcoholInteractionDescription");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("alcohol_nteraction")]
        public bool AlcoholNteraction 
        { 
            get 
            {
                return this.alcoholNteraction; 
            } 
            set 
            {
                this.alcoholNteraction = value;
                onPropertyChanged("AlcoholNteraction");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 