/*
 * HealthOS.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using HealthOS.UWP;
using HealthOS.UWP.Utilities;

namespace HealthOS.UWP.Models
{
    public class DiseasesResponse : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string diseaseName;
        private string diseaseCat;
        private string diseaseInfo;
        private string diseaseId;
        private double searchScore;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("disease_name")]
        public string DiseaseName 
        { 
            get 
            {
                return this.diseaseName; 
            } 
            set 
            {
                this.diseaseName = value;
                onPropertyChanged("DiseaseName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("disease_cat")]
        public string DiseaseCat 
        { 
            get 
            {
                return this.diseaseCat; 
            } 
            set 
            {
                this.diseaseCat = value;
                onPropertyChanged("DiseaseCat");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("disease_info")]
        public string DiseaseInfo 
        { 
            get 
            {
                return this.diseaseInfo; 
            } 
            set 
            {
                this.diseaseInfo = value;
                onPropertyChanged("DiseaseInfo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("disease_id")]
        public string DiseaseId 
        { 
            get 
            {
                return this.diseaseId; 
            } 
            set 
            {
                this.diseaseId = value;
                onPropertyChanged("DiseaseId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("search_score")]
        public double SearchScore 
        { 
            get 
            {
                return this.searchScore; 
            } 
            set 
            {
                this.searchScore = value;
                onPropertyChanged("SearchScore");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 