/*
 * HealthOS.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using HealthOS.UWP;
using HealthOS.UWP.Utilities;

namespace HealthOS.UWP.Models
{
    public class RequestAccessTokenRequest : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string grantType;
        private string clientId;
        private string clientSecret;
        private string scope;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("grant_type")]
        public string GrantType 
        { 
            get 
            {
                return this.grantType; 
            } 
            set 
            {
                this.grantType = value;
                onPropertyChanged("GrantType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("client_id")]
        public string ClientId 
        { 
            get 
            {
                return this.clientId; 
            } 
            set 
            {
                this.clientId = value;
                onPropertyChanged("ClientId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("client_secret")]
        public string ClientSecret 
        { 
            get 
            {
                return this.clientSecret; 
            } 
            set 
            {
                this.clientSecret = value;
                onPropertyChanged("ClientSecret");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("scope")]
        public string Scope 
        { 
            get 
            {
                return this.scope; 
            } 
            set 
            {
                this.scope = value;
                onPropertyChanged("Scope");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 