/*
 * HealthOS.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using HealthOS.UWP;
using HealthOS.UWP.Utilities;

namespace HealthOS.UWP.Models
{
    public class SearchLabTestsResponse : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string alternateName;
        private LabTestData labTestData;
        private string labTestId;
        private string labTestName;
        private string id;
        private double searchScore;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("alternate_name")]
        public string AlternateName 
        { 
            get 
            {
                return this.alternateName; 
            } 
            set 
            {
                this.alternateName = value;
                onPropertyChanged("AlternateName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lab_test_data")]
        public LabTestData LabTestData 
        { 
            get 
            {
                return this.labTestData; 
            } 
            set 
            {
                this.labTestData = value;
                onPropertyChanged("LabTestData");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lab_test_id")]
        public string LabTestId 
        { 
            get 
            {
                return this.labTestId; 
            } 
            set 
            {
                this.labTestId = value;
                onPropertyChanged("LabTestId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lab_test_name")]
        public string LabTestName 
        { 
            get 
            {
                return this.labTestName; 
            } 
            set 
            {
                this.labTestName = value;
                onPropertyChanged("LabTestName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("search_score")]
        public double SearchScore 
        { 
            get 
            {
                return this.searchScore; 
            } 
            set 
            {
                this.searchScore = value;
                onPropertyChanged("SearchScore");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 