/*
 * HealthOS.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using HealthOS.UWP;
using HealthOS.UWP.Utilities;

namespace HealthOS.UWP.Models
{
    public class SearchFoodBrandsResponse : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string logo;
        private string name;
        private string foodBrandId;
        private double searchScore;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("logo")]
        public string Logo 
        { 
            get 
            {
                return this.logo; 
            } 
            set 
            {
                this.logo = value;
                onPropertyChanged("Logo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("food_brand_id")]
        public string FoodBrandId 
        { 
            get 
            {
                return this.foodBrandId; 
            } 
            set 
            {
                this.foodBrandId = value;
                onPropertyChanged("FoodBrandId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("search_score")]
        public double SearchScore 
        { 
            get 
            {
                return this.searchScore; 
            } 
            set 
            {
                this.searchScore = value;
                onPropertyChanged("SearchScore");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 