/*
 * HealthOS.UWP
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using HealthOS.UWP;
using HealthOS.UWP.Utilities;

namespace HealthOS.UWP.Models
{
    public class SearchExercisesResponse16 : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string name;
        private string category;
        private string caloryCount;
        private string cardioSubcategory;
        private string primaryMuscleGroup;
        private string exerciseId;
        private double searchScore;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("category")]
        public string Category 
        { 
            get 
            {
                return this.category; 
            } 
            set 
            {
                this.category = value;
                onPropertyChanged("Category");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("calory_count")]
        public string CaloryCount 
        { 
            get 
            {
                return this.caloryCount; 
            } 
            set 
            {
                this.caloryCount = value;
                onPropertyChanged("CaloryCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cardio_subcategory")]
        public string CardioSubcategory 
        { 
            get 
            {
                return this.cardioSubcategory; 
            } 
            set 
            {
                this.cardioSubcategory = value;
                onPropertyChanged("CardioSubcategory");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("primary_muscle_group")]
        public string PrimaryMuscleGroup 
        { 
            get 
            {
                return this.primaryMuscleGroup; 
            } 
            set 
            {
                this.primaryMuscleGroup = value;
                onPropertyChanged("PrimaryMuscleGroup");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("exercise_id")]
        public string ExerciseId 
        { 
            get 
            {
                return this.exerciseId; 
            } 
            set 
            {
                this.exerciseId = value;
                onPropertyChanged("ExerciseId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("search_score")]
        public double SearchScore 
        { 
            get 
            {
                return this.searchScore; 
            } 
            set 
            {
                this.searchScore = value;
                onPropertyChanged("SearchScore");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 